### PR TITLE
Type hinting for Poll Writer draw() function

### PR DESCRIPTION
**Pull request by obiefy**
There is some testing challenges on test cases. this bellow test functions on poll ashboard testcase did not pass for me: 
- an_admin_can_add_a_poll 
- an_admin_can_modify_poll_type 
- an_admin_can_close_a_poll 
- an_admin_can_reopen_a_closed_poll

### CODE REVIEW

**Comment by akiyamaSM** [comment]
Thanks @obiefy, Actually the tests are not updated, that's why probably a huge number of them won't pass. I'll take a look on your changes and give you a feed back asap.

**Comment by akiyamaSM** [comment]
Sorry @obiefy but it would be nice if you can make multiple PR that way it would be easy to handle each case.
For tests I think I'll have to re-make them.

**Comment by obiefy** [comment]
Do you face any problem with merging this PR?

**Comment by akiyamaSM** [comment]
@obiefy There are many changes, I can't merge with no tests. that's why it would be better if it's just minor changes per PR.

**Comment by obiefy** [comment]
@akiyamaSM I created a test function for draw function changes. and it passed, and of course, I checked all test suite and it passed except the 4 functions that I mentioned before.
so all the changes have been tested.
The only thing that makes this PR has a lot of changes is the code reformat.
It will be nice if you have a closer look at this PR again.

**Pull request merged**
